SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

DROP DATABASE IF EXISTS TEST;
CREATE DATABASE TEST;

DROP TABLE IF EXISTS LOGIN;
CREATE TABLE LOGIN(
	id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	Login VARCHAR(100),
	MotDePasse VARCHAR(100)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO LOGIN (Login, MotDePasse) VALUES
('admin','admin');